apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: intranet-demo
  namespace: intranet-demo
spec:
  selector:
    matchLabels:
      app: intranet-demo
  podMetricsEndpoints:
  - port: http
    path: "/metrics/fpm"
    interval: 15s
