sudo: required

services:
  - docker

before_install:
  - sudo pip install awscli
  - cd docker

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop

script:
  - make smoketest
