version: '3.5'
services:
  wordpress:
    build: .
    cap_add:
      - SYS_ADMIN
    container_name: wordpress
    depends_on:
      - mailcatcher
      - mysql
    devices:
      - /dev/fuse
    env_file: .env
    environment:
      development: 1
      WP_ENV: development
      VIRTUAL_HOST: intranet.docker
      SMTP_HOST: mailcatcher
      SMTP_PORT: 1025
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_HOST: mysql
    links:
      - mailcatcher
      - mysql
    ports:
      - "80:80"
  mysql:
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    image: mariadb
    logging:
      driver: none
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
      - ./db-dump:/docker-entrypoint-initdb.d
  mailcatcher:
    container_name: mailcatcher
    environment:
      VIRTUAL_HOST: mail.intranet.docker
      VIRTUAL_PORT: 1080
    image: ministryofjustice/mailcatcher
    logging:
      driver: none
    ports:
      - "1080:1080"
volumes:
  database:
    driver: local
