version: "3.8"

volumes:
  node_modules: ~
  dist: ~
  minio_storage: ~
  local_ssh: ~
  elasticsearch-data:
  database:
    driver: local

services:
  php-fpm:
    build:
      context: .
      target: dev
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
      - minio

  nginx:
    build:
      context: .
      target: nginx-dev
    volumes:
      - dist:/var/www/html/public/app/themes/clarity/dist
      - ./deploy/config/local/php-fpm.conf:/etc/nginx/php-fpm.conf
      - ./deploy/config/local/server.conf:/etc/nginx/conf.d/default.conf
      - ./public/index.php:/var/www/html/public/index.php
      - ./public/wp/wp-admin/index.php:/var/www/html/public/wp/wp-admin/index.php
    environment:
      VIRTUAL_HOST: ${SERVER_NAME}
      VIRTUAL_PORT: 8080
      SERVER_NAME: ${SERVER_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - php-fpm
      - node

  node:
    image: node:20
    working_dir: /node
    entrypoint: make
    command: node-assets
    volumes:
      - node_modules:/node/node_modules
      - dist:/node/dist
      - ./Makefile:/node/Makefile
      - ./public/app/themes/clarity/src:/node/src
      - ./public/app/themes/clarity/jsconfig.json:/node/jsconfig.json
      - ./public/app/themes/clarity/package.json:/node/package.json
      - ./public/app/themes/clarity/package-lock.json:/node/package-lock.json
      - ./public/app/themes/clarity/webpack.mix.js:/node/webpack.mix.js

  mariadb:
    image: mariadb:10
    healthcheck:
      test: [ "CMD-SHELL", "bash", "-c", "echo > /dev/tcp/localhost/3306" ]
      interval: 1s
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
      VIRTUAL_HOST: minio.${SERVER_NAME}
      VIRTUAL_PORT: 9000
    command: server --console-address ":9001" /data
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 2

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: |
      /bin/sh -c "
        mc config host add intranet http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY}
        mc mb intranet/${S3_BUCKET_NAME}
        mc anonymous set download intranet/${S3_BUCKET_NAME};
        exit 0
      "

  cdn:
    image: caddy:2.7.6-alpine
    volumes:
      - ./deploy/config/local/Caddyfile:/etc/caddy/Caddyfile
    environment:
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      VIRTUAL_HOST: cdn.${SERVER_NAME}
      VIRTUAL_PORT: 2019
    depends_on:
      - minio

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    ports:
      - "9191:80"
    links:
      - mariadb

  elasticsearch:
    container_name: intranet-elasticsearch
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      VIRTUAL_HOST: elasticsearch.${SERVER_NAME}
      VIRTUAL_PORT: 9200
      xpack.security.enabled: false
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    container_name: intranet-kibana
    image: kibana:${ELASTICSEARCH_VERSION}
    environment:
      VIRTUAL_HOST: kibana.${SERVER_NAME}
      VIRTUAL_PORT: 5601
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOST}
    ports:
      - "5610:5610"
    depends_on:
      - elasticsearch