apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: intranet-local
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: intranet-local
  minReplicas: 2
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20