apiVersion: v1
kind: ConfigMap
metadata:
  name: intranet-dev
  namespace: intranet-dev
data:
  WP_ENV: "development"
  WP_HOME: 'https://dev.intranet.justice.gov.uk'
  WP_SITEURL: 'https://dev.intranet.justice.gov.uk/wp'
  AWS_CLOUDFRONT_HOST: 'cdn.dev.intranet.justice.gov.uk'
  # See Azure Setup for more information on how to get these values.
  OAUTH_CLIENT_ID: "1dac3cbf-91d2-4c0e-9c80-0bf3f8fabd75"
  OAUTH_TENANT_ID: "c6874728-71e6-41fe-a9e1-2e8c36776ad8"
  # IP addresses, with optional CIDR notation. Separated by newlines and using # for comments.
  ALLOWED_IPS: |
    # Global Protect
    18.169.147.172
    35.176.93.186
    18.130.148.126
    35.176.148.126
