apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: intranet-dev
  namespace: intranet-dev
spec:
  selector:
    matchLabels:
      app: intranet-dev
  podMetricsEndpoints:
  - port: nginx-port
    path: "/status?openmetrics"
    interval: 15s