apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: intranet-dev
  namespace: intranet-dev
spec:
  selector:
    matchLabels:
      app: intranet-dev
  endpoints:
  - port: http
    interval: 15s
    path: /metrics/service
