version: '3.3'
services:
  wordpress:
    container_name: smoketest_wp_local_dev
    build: .
    env_file: .env
    environment:
      development: 1
      WP_ENV: development
      VIRTUAL_HOST: intranet.docker
      SMTP_HOST: mailcatcher
      SMTP_PORT: 1025
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_HOST: mysql
    command: ["/build.sh"]
    links:
      - mailcatcher
      - mysql
    depends_on:
      - mailcatcher
      - mysql
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    ports:
      - "80:80"
  mysql:
    container_name: smoketest_wp_local_db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - database:/var/lib/mysql
      - ./db-dump:/db-dump
    ports:
      - "3306:3306"
  mailcatcher:
    container_name: smoketest_wp_local_smtp
    image: ministryofjustice/mailcatcher
    environment:
      VIRTUAL_HOST: mail.intranet.docker
      VIRTUAL_PORT: 1080
    ports:
      - "1080:1080"
  smoketest:
    build: ../smoke-tests
    links:
      - wordpress:intranet.docker
    depends_on:
      - wordpress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_CONTAINER: smoketest_wp_local_dev
    #command: ["cucumber -c"]
volumes:
  database:
    driver: local
