version: '3.3'
services:
  wordpress:
    container_name: wp_local_dev
    build: .
    env_file: .env
    volumes:
      - ./bedrock_volume:/bedrock
    environment:
      development: 1
      WP_ENV: development
      VIRTUAL_HOST: intranet.docker
      SMTP_HOST: mailcatcher
      SMTP_PORT: 1025
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_HOST: mysql
    command: ["/build.sh"]
    links:
      - mailcatcher
      - mysql
    depends_on:
      - mailcatcher
      - mysql
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    ports:
      - "80:80"
  mysql:
    container_name: wp_local_db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - database:/var/lib/mysql
      - ./db-dump:/db-dump
  mailcatcher:
    container_name: wp_local_smtp
    image: schickling/mailcatcher
    environment:
      VIRTUAL_HOST: mail.intranet.docker
      VIRTUAL_PORT: 1080
volumes:
  database:
    driver: local
