apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: intranet-staging
  namespace: intranet-staging
spec:
  selector:
    matchLabels:
      app: intranet-staging
  endpoints:
  - port: http
    interval: 15s
    path: /metrics/service
