name: Deploy to MoJ Cloud Platform

on:
  workflow_dispatch:
  push:
    branches:
      # - 'main' # protect main during initial development
      - 'develop'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image:
    name: "Image"
    if: github.event.ref == 'refs/heads/develop'
    uses: ./.github/workflows/build.yml
    secrets: inherit

  get_ip_ranges:
    name: "IP Ranges"
    if: github.event.ref == 'refs/heads/develop'
    uses: ./.github/workflows/ip-ranges-configure.yml
    secrets: inherit

  deploy_dev:
    name: "Development"
    if: github.event.ref == 'refs/heads/develop'
    uses: ./.github/workflows/deploy.yml
    needs: [image, get_ip_ranges]
    with:
      environment: development
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit

  deploy_staging:
    name: "Staging"
    needs: [image, deploy_dev, get_ip_ranges]
    if: github.event.ref == 'refs/heads/develop'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit

  deploy_demo:
    name: "Demo"
    needs: [image, deploy_dev, get_ip_ranges]
    if: github.event.ref == 'refs/heads/develop'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: demo
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit

  deploy_production:
    name: "Production"
    needs: [image, deploy_staging, get_ip_ranges]
    if: github.event.ref == 'refs/heads/develop'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit
