name: "Get IP ranges"

on:
  workflow_call:
    outputs:
      ip_ranges:
        description: "IPs Ranges"
        value: ${{ jobs.get_ip_ranges.outputs.ip_ranges }}
      ips_formatted:
        description: "IPs Ranges (formatted)"
        value: ${{ jobs.get_ip_ranges.outputs.ips_formatted }}

jobs:
  get_ip_ranges:
    name: "Build"
    runs-on: ubuntu-latest
    outputs:
      ip_ranges: ${{ steps.get-ips.outputs.ip_ranges }}
      ips_formatted: ${{ steps.get-ips.outputs.ips_formatted }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: 'ministryofjustice/moj-ip-addresses'
          ref: 'main'
          # This is a fine grained PAT, it's scoped to the moj-ip private repository 
          # with the single permission: Content: Read-only.
          # The token is pending approval: https://github.com/settings/personal-access-tokens/3669004
          token: ${{ secrets.MOJ_IP_ADDRESSES_RO_PAT }}
      - name: "Get & format IPs"
        id: get-ips
        uses: mikefarah/yq@master
        with:
          cmd: |
            IP_RANGES=$(yq 'explode(.) | {"deprecating": .deprecating_access_to_moj_intranet | flatten, "allow": .allow_access_to_moj_intranet | flatten }' -o json -I=0 moj-cidr-addresses.yml)
            echo "ip_ranges=$IP_RANGES" >> $GITHUB_OUTPUT

            # Transform into nginx geo format. 1 IP range per line, each range is followed by it's value.
            # @see https://nginx.org/en/docs/http/ngx_http_geo_module.html
            ALLOW_VALUE=1
            DEPRI_VALUE=2

            ALLOW_FORMATTED=$(yq 'explode(.) | .allow_access_to_moj_intranet       | flatten | map(. + " '$ALLOW_VALUE';") | join("\n")' moj-cidr-addresses.yml)
            DEPRI_FORMATTED=$(yq 'explode(.) | .deprecating_access_to_moj_intranet | flatten | map(. + " '$DEPRI_VALUE';") | join("\n")' moj-cidr-addresses.yml)

            echo "ips_formatted=$ALLOW_FORMATTED"$'\n'"$DEPRI_FORMATTED" >> $GITHUB_OUTPUT
