name: 'Check Branch'

on:
    pull_request:

jobs:
    check_branch:
        runs-on: ubuntu-latest
        steps:
            - name: Check branch
              if: github.base_ref == 'main' && github.head_ref != 'develop'
              run: |
                  echo "ERROR: You can only merge to main from develop. Please, QA before releasing to main."
                  exit 1
